/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencimientosRouteImport } from './routes/vencimientos'
import { Route as CausasRouteImport } from './routes/causas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CausasIdRouteImport } from './routes/causas.$id'

const VencimientosRoute = VencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const CausasRoute = CausasRouteImport.update({
  id: '/causas',
  path: '/causas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausasIdRoute = CausasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CausasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/causas': typeof CausasRouteWithChildren
  '/vencimientos': typeof VencimientosRoute
  '/causas/$id': typeof CausasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/causas': typeof CausasRouteWithChildren
  '/vencimientos': typeof VencimientosRoute
  '/causas/$id': typeof CausasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/causas': typeof CausasRouteWithChildren
  '/vencimientos': typeof VencimientosRoute
  '/causas/$id': typeof CausasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/causas' | '/vencimientos' | '/causas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/causas' | '/vencimientos' | '/causas/$id'
  id: '__root__' | '/' | '/causas' | '/vencimientos' | '/causas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CausasRoute: typeof CausasRouteWithChildren
  VencimientosRoute: typeof VencimientosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencimientos': {
      id: '/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof VencimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causas': {
      id: '/causas'
      path: '/causas'
      fullPath: '/causas'
      preLoaderRoute: typeof CausasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causas/$id': {
      id: '/causas/$id'
      path: '/$id'
      fullPath: '/causas/$id'
      preLoaderRoute: typeof CausasIdRouteImport
      parentRoute: typeof CausasRoute
    }
  }
}

interface CausasRouteChildren {
  CausasIdRoute: typeof CausasIdRoute
}

const CausasRouteChildren: CausasRouteChildren = {
  CausasIdRoute: CausasIdRoute,
}

const CausasRouteWithChildren =
  CausasRoute._addFileChildren(CausasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CausasRoute: CausasRouteWithChildren,
  VencimientosRoute: VencimientosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
