/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencimientosRouteImport } from './routes/vencimientos'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CausasRouteImport } from './routes/causas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CausasIndexRouteImport } from './routes/causas.index'
import { Route as CausasIdRouteImport } from './routes/causas.$id'

const VencimientosRoute = VencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CausasRoute = CausasRouteImport.update({
  id: '/causas',
  path: '/causas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausasIndexRoute = CausasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CausasRoute,
} as any)
const CausasIdRoute = CausasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CausasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/causas': typeof CausasRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/tareas': typeof TareasRoute
  '/vencimientos': typeof VencimientosRoute
  '/causas/$id': typeof CausasIdRoute
  '/causas/': typeof CausasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/tareas': typeof TareasRoute
  '/vencimientos': typeof VencimientosRoute
  '/causas/$id': typeof CausasIdRoute
  '/causas': typeof CausasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/causas': typeof CausasRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/tareas': typeof TareasRoute
  '/vencimientos': typeof VencimientosRoute
  '/causas/$id': typeof CausasIdRoute
  '/causas/': typeof CausasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/causas'
    | '/clientes'
    | '/configuracion'
    | '/equipo'
    | '/login'
    | '/tareas'
    | '/vencimientos'
    | '/causas/$id'
    | '/causas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/equipo'
    | '/login'
    | '/tareas'
    | '/vencimientos'
    | '/causas/$id'
    | '/causas'
  id:
    | '__root__'
    | '/'
    | '/causas'
    | '/clientes'
    | '/configuracion'
    | '/equipo'
    | '/login'
    | '/tareas'
    | '/vencimientos'
    | '/causas/$id'
    | '/causas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CausasRoute: typeof CausasRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EquipoRoute: typeof EquipoRoute
  LoginRoute: typeof LoginRoute
  TareasRoute: typeof TareasRoute
  VencimientosRoute: typeof VencimientosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencimientos': {
      id: '/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof VencimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causas': {
      id: '/causas'
      path: '/causas'
      fullPath: '/causas'
      preLoaderRoute: typeof CausasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causas/': {
      id: '/causas/'
      path: '/'
      fullPath: '/causas/'
      preLoaderRoute: typeof CausasIndexRouteImport
      parentRoute: typeof CausasRoute
    }
    '/causas/$id': {
      id: '/causas/$id'
      path: '/$id'
      fullPath: '/causas/$id'
      preLoaderRoute: typeof CausasIdRouteImport
      parentRoute: typeof CausasRoute
    }
  }
}

interface CausasRouteChildren {
  CausasIdRoute: typeof CausasIdRoute
  CausasIndexRoute: typeof CausasIndexRoute
}

const CausasRouteChildren: CausasRouteChildren = {
  CausasIdRoute: CausasIdRoute,
  CausasIndexRoute: CausasIndexRoute,
}

const CausasRouteWithChildren =
  CausasRoute._addFileChildren(CausasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CausasRoute: CausasRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EquipoRoute: EquipoRoute,
  LoginRoute: LoginRoute,
  TareasRoute: TareasRoute,
  VencimientosRoute: VencimientosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
